controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_index:
   path:  /index/{name}
   controller: App\Controller\HomeController::index
   requirements:
   name: '\d+'
